#!/usr/bin/env bash
# DSP operator menu — update, configure, and run without memorizing CLI flags.
set -uo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
DEFAULT_REPO_DIR="${SCRIPT_DIR}"

CONFIG_DIR="${HOME}/.dsp"
CONFIG_FILE="${CONFIG_DIR}/config.env"
RUNS_DIR="${HOME}/.dsp/runs"
RELEASE_BRANCH="release/v1.4.0"

# shellcheck disable=SC2034
MENU_ITEMS=(
  "1:Update latest patch"
  "2:Configure environment"
  "3:Run scenario"
  "4:Show latest report"
  "5:Show version/status"
  "6:Exit"
)

has_whiptail() {
  command -v whiptail >/dev/null 2>&1
}

show_webshell_setup_help() {
  # Plain msgbox (no --scrolltext): focus stays on <Ok>, no scroll arrow.
  whiptail --title "Configure — Webshell help" --msgbox \
"Webshell remote execution — what to enter

[1] Webshell family (pick one)
  jsp   Java/Tomcat shell file (.jsp)
  php   PHP shell file (.php)
  aspx  IIS/ASP.NET shell file (.aspx)

[2] Webshell URL — full HTTP(S) address of that file
  http://10.10.10.50:8080/shell.jsp
  http://10.10.10.50/shell.php
  https://lab.example/path/shell.aspx
  Tip: extension must match family (jsp/php/aspx).

[3] Remote work directory — writable folder on the target host
  /tmp/dsp
  /var/tmp/dsp
  DSP uploads scripts and events here via the shell." \
    20 78 2>/dev/null || true
}

normalize_webshell_family() {
  local raw="${1,,}"
  case "$raw" in
    jsp | php | aspx) printf '%s' "$raw" ;;
    *)
      err "Webshell family must be jsp, php, or aspx (got: ${1})"
      return 1
      ;;
  esac
}

msg() {
  local text="$1"
  if has_whiptail; then
    whiptail --title "DSP Menu" --msgbox "$text" 12 72 2>/dev/null || true
  else
    printf '%s\n' "$text"
    read -r -p "Press Enter to continue..."
  fi
}

err() {
  local text="$1"
  if has_whiptail; then
    whiptail --title "DSP Menu — Error" --msgbox "$text" 12 72 2>/dev/null || true
  else
    printf 'ERROR: %s\n' "$text" >&2
    read -r -p "Press Enter to continue..."
  fi
}

ensure_config_dir() {
  mkdir -p "$CONFIG_DIR"
}

write_default_config() {
  ensure_config_dir
  cat >"$CONFIG_FILE" <<EOF
# DSP operator menu configuration (generated by dsp-menu.sh)
DSP_REPO_DIR=${DEFAULT_REPO_DIR}
TARGET_NET=10.10.10.0/24
EXECUTION_MODE=local
PROFILE=normal
WEBSHELL_FAMILY=jsp
WEBSHELL_URL=http://10.10.10.50:8080/shell.jsp
REMOTE_WORK_DIR=/tmp/dsp
EOF
}

load_config() {
  DSP_REPO_DIR="$DEFAULT_REPO_DIR"
  TARGET_NET="10.10.10.0/24"
  EXECUTION_MODE="local"
  PROFILE="normal"
  WEBSHELL_FAMILY="jsp"
  WEBSHELL_URL="http://10.10.10.50:8080/shell.jsp"
  REMOTE_WORK_DIR="/tmp/dsp"

  if [[ ! -f "$CONFIG_FILE" ]]; then
    write_default_config
  fi

  # shellcheck disable=SC1090
  source "$CONFIG_FILE"

  # Legacy profile names (low removed; balanced/burst aliases).
  case "${PROFILE,,}" in
    low|balanced) PROFILE="normal" ;;
    burst) PROFILE="high" ;;
  esac

  if [[ ! -d "$DSP_REPO_DIR" ]]; then
    DSP_REPO_DIR="$DEFAULT_REPO_DIR"
  fi
}

save_config() {
  ensure_config_dir
  cat >"$CONFIG_FILE" <<EOF
# DSP operator menu configuration (generated by dsp-menu.sh)
DSP_REPO_DIR=${DSP_REPO_DIR}
TARGET_NET=${TARGET_NET}
EXECUTION_MODE=${EXECUTION_MODE}
PROFILE=${PROFILE}
WEBSHELL_FAMILY=${WEBSHELL_FAMILY}
WEBSHELL_URL=${WEBSHELL_URL}
REMOTE_WORK_DIR=${REMOTE_WORK_DIR}
EOF
}

activate_dsp_env() {
  if [[ -f "${DSP_REPO_DIR}/.venv/bin/activate" ]]; then
    # shellcheck disable=SC1091
    source "${DSP_REPO_DIR}/.venv/bin/activate"
  fi
  export PATH="${DSP_REPO_DIR}/.venv/bin:${PATH}"
}

show_menu_whiptail() {
  whiptail --title "DSP Menu" --menu "Detection Scenario Platform" 18 72 10 \
    "1" "Update latest patch" \
    "2" "Configure environment" \
    "3" "Run scenario" \
    "4" "Show latest report" \
    "5" "Show version/status" \
    "6" "Exit" \
    3>&1 1>&2 2>&3
}

show_menu_plain() {
  printf '\n=== DSP Menu ===\n'
  printf '1) Update latest patch\n'
  printf '2) Configure environment\n'
  printf '3) Run scenario\n'
  printf '4) Show latest report\n'
  printf '5) Show version/status\n'
  printf '6) Exit\n'
  printf 'Choice [1-6]: '
  read -r choice
  printf '%s' "$choice"
}

pick_choice() {
  if has_whiptail; then
    show_menu_whiptail || return 1
  else
    show_menu_plain
  fi
}

do_update() {
  load_config
  local log
  log="$(mktemp)"
  {
    printf 'Repository: %s\n' "$DSP_REPO_DIR"
    printf 'Branch: %s\n\n' "$RELEASE_BRANCH"
    if [[ ! -d "${DSP_REPO_DIR}/.git" ]]; then
      printf 'ERROR: %s is not a git repository.\n' "$DSP_REPO_DIR"
      exit 1
    fi
    cd "$DSP_REPO_DIR"
    git fetch origin
    git checkout "$RELEASE_BRANCH"
    git pull origin "$RELEASE_BRANCH"
    printf '\nUpdate complete.\n'
    git log -1 --oneline
  } >"$log" 2>&1 || true

  if has_whiptail; then
    whiptail --title "Update latest patch" --scrolltext --textbox "$log" 20 72 2>/dev/null || true
  else
    cat "$log"
    read -r -p "Press Enter to continue..."
  fi
  rm -f "$log"
}

configure_whiptail() {
  local value

  value="$(whiptail --title "Configure" --inputbox \
"Target network in CIDR notation.

Examples:
  10.10.10.0/24     (lab subnet)
  192.168.56.0/24" \
    14 78 "$TARGET_NET" 3>&1 1>&2 2>&3)" || return 1
  TARGET_NET="${value//$'\n'/}"

  # Use --menu (not --radiolist): radiolist needs Space to toggle ON, so Enter alone
  # often leaves "local" selected even when the cursor is on webshell.
  value="$(whiptail --title "Configure" --menu "Execution mode" 12 72 2 \
    --default-item "$EXECUTION_MODE" \
    "local" "Run from this host" \
    "webshell" "Run via webshell provider" \
    3>&1 1>&2 2>&3)" || return 1
  EXECUTION_MODE="${value//$'\n'/}"

  if [[ "$EXECUTION_MODE" == "webshell" ]]; then
    show_webshell_setup_help

    value="$(whiptail --title "Configure" --menu \
"Webshell family — shell type on the target host.
Extension in the URL must match." \
      14 78 3 \
      --default-item "$WEBSHELL_FAMILY" \
      "jsp" "Java/Tomcat  e.g. http://host:8080/shell.jsp" \
      "php" "PHP         e.g. http://host/shell.php" \
      "aspx" "IIS/ASP.NET e.g. http://host/shell.aspx" \
      3>&1 1>&2 2>&3)" || return 1
    WEBSHELL_FAMILY="${value//$'\n'/}"

    value="$(whiptail --title "Configure" --inputbox \
"Full HTTP(S) URL of the webshell file.

Examples (match family ${WEBSHELL_FAMILY}):
  http://10.10.10.50:8080/shell.${WEBSHELL_FAMILY}
  http://192.168.1.10:80/cmd.${WEBSHELL_FAMILY}
  https://lab.example/webshell/shell.${WEBSHELL_FAMILY}" \
      16 78 "$WEBSHELL_URL" 3>&1 1>&2 2>&3)" || return 1
    WEBSHELL_URL="${value//$'\n'/}"

    value="$(whiptail --title "Configure" --inputbox \
"Writable directory on the webshell host.
DSP uploads run_scenario.py and events here.

Examples:
  /tmp/dsp
  /var/tmp/dsp" \
      14 78 "$REMOTE_WORK_DIR" 3>&1 1>&2 2>&3)" || return 1
    REMOTE_WORK_DIR="${value//$'\n'/}"
  fi

  value="$(whiptail --title "Configure" --menu "Traffic profile" 14 72 2 \
    --default-item "$PROFILE" \
    "normal" "Default — limited representative targets" \
    "high" "Same volume, all discovered targets" \
    3>&1 1>&2 2>&3)" || return 1
  PROFILE="${value//$'\n'/}"

  value="$(whiptail --title "Configure" --inputbox "DSP repository directory" 10 72 "$DSP_REPO_DIR" 3>&1 1>&2 2>&3)" || return 1
  DSP_REPO_DIR="${value//$'\n'/}"

  save_config
  msg "Configuration saved to ${CONFIG_FILE}"
}

configure_plain() {
  local value

  read -r -p "Target network [${TARGET_NET}]: " value
  [[ -n "$value" ]] && TARGET_NET="$value"

  printf 'Execution mode (local/webshell) [%s]: ' "$EXECUTION_MODE"
  read -r value
  [[ -n "$value" ]] && EXECUTION_MODE="$value"

  if [[ "$EXECUTION_MODE" == "webshell" ]]; then
    printf '\n--- Webshell setup ---\n'
    printf 'Family: jsp | php | aspx (must match shell file extension)\n'
    printf '  jsp   -> http://host:8080/shell.jsp\n'
    printf '  php   -> http://host/shell.php\n'
    printf '  aspx  -> http://host/shell.aspx\n'
    printf 'Webshell family (jsp/php/aspx) [%s]: ' "$WEBSHELL_FAMILY"
    read -r value
    if [[ -n "$value" ]]; then
      WEBSHELL_FAMILY="$(normalize_webshell_family "$value")" || return 0
    fi

    printf 'Webshell URL (full http(s) address) [%s]: ' "$WEBSHELL_URL"
    read -r value
    [[ -n "$value" ]] && WEBSHELL_URL="$value"

    printf 'Remote work dir on target host (e.g. /tmp/dsp) [%s]: ' "$REMOTE_WORK_DIR"
    read -r value
    [[ -n "$value" ]] && REMOTE_WORK_DIR="$value"
    printf '\n'
  fi

  printf 'Profile (normal/high) [%s]: ' "$PROFILE"
  read -r value
  [[ -n "$value" ]] && PROFILE="$value"

  printf 'DSP repo dir [%s]: ' "$DSP_REPO_DIR"
  read -r value
  [[ -n "$value" ]] && DSP_REPO_DIR="$value"

  save_config
  msg "Configuration saved to ${CONFIG_FILE}"
}

do_configure() {
  load_config
  if has_whiptail; then
    configure_whiptail || true
  else
    configure_plain
  fi
}

do_run() {
  load_config
  activate_dsp_env

  if ! command -v dsp >/dev/null 2>&1; then
    err "dsp command not found. Install with: cd ${DSP_REPO_DIR} && python3 -m venv .venv && .venv/bin/pip install -e ."
    return
  fi

  local log rc
  log="$(mktemp)"

  # Stream progress to the terminal (not only a post-run textbox). Redirecting
  # all output to a temp file made long runs look frozen with no feedback.
  printf '\n=== DSP scenario run ===\n' | tee "$log"
  printf 'Profile: %s\n' "$PROFILE" | tee -a "$log"
  printf 'Target net: %s\n' "$TARGET_NET" | tee -a "$log"
  printf 'Execution mode: %s\n' "$EXECUTION_MODE" | tee -a "$log"
  printf 'Live verbose output below — discovery and each scenario action are shown.\n\n' | tee -a "$log"

  cd "$DSP_REPO_DIR" || {
    err "Cannot cd to ${DSP_REPO_DIR}"
    rm -f "$log"
    return
  }

  export PYTHONUNBUFFERED=1
  local dsp_args=(--verbose --profile "$PROFILE" --target-net "$TARGET_NET")
  if [[ "$EXECUTION_MODE" == "webshell" ]]; then
    dsp run \
      "${dsp_args[@]}" \
      --execution-provider webshell \
      --webshell-family "$WEBSHELL_FAMILY" \
      --webshell-url "$WEBSHELL_URL" \
      --remote-work-dir "$REMOTE_WORK_DIR" 2>&1 | tee -a "$log"
  else
    dsp run "${dsp_args[@]}" 2>&1 | tee -a "$log"
  fi
  rc=${PIPESTATUS[0]}

  printf '\n=== Run finished (exit %s) ===\n' "$rc" | tee -a "$log"

  if has_whiptail; then
    whiptail --title "Run scenario (exit ${rc})" --scrolltext --textbox "$log" 22 78 2>/dev/null || true
  else
    read -r -p "Press Enter to continue..."
  fi
  rm -f "$log"
}

format_json_file() {
  local file="$1"
  if command -v python3 >/dev/null 2>&1; then
    python3 -m json.tool "$file" 2>/dev/null || cat "$file"
  else
    cat "$file"
  fi
}

do_show_report() {
  load_config
  local latest log
  log="$(mktemp)"

  if [[ ! -d "$RUNS_DIR" ]]; then
    printf 'No runs directory: %s\n' "$RUNS_DIR" >"$log"
  else
    latest="$(ls -td "${RUNS_DIR}"/* 2>/dev/null | head -1 || true)"
    if [[ -z "$latest" ]]; then
      printf 'No run directories under %s\n' "$RUNS_DIR" >"$log"
    else
      {
        printf 'Run directory:\n  %s\n\n' "$latest"
        if [[ -f "${latest}/traffic_summary.json" ]]; then
          printf '--- traffic_summary.json ---\n'
          format_json_file "${latest}/traffic_summary.json"
          printf '\n'
        else
          printf 'traffic_summary.json: (not found)\n\n'
        fi
        if [[ -f "${latest}/report.md" ]]; then
          printf 'report.md:\n  %s\n' "${latest}/report.md"
        else
          printf 'report.md: (not found)\n'
        fi
        if [[ -f "${latest}/verification_checklist.md" ]]; then
          printf 'verification_checklist.md:\n  %s\n' "${latest}/verification_checklist.md"
        else
          printf 'verification_checklist.md: (not found)\n'
        fi
      } >"$log"
    fi
  fi

  if has_whiptail; then
    whiptail --title "Latest report" --scrolltext --textbox "$log" 22 78 2>/dev/null || true
  else
    cat "$log"
    read -r -p "Press Enter to continue..."
  fi
  rm -f "$log"
}

do_show_status() {
  load_config
  activate_dsp_env

  local log
  log="$(mktemp)"
  {
    printf '=== Git ===\n'
    if [[ -d "${DSP_REPO_DIR}/.git" ]]; then
      cd "$DSP_REPO_DIR"
      printf 'Repo: %s\n' "$DSP_REPO_DIR"
      git branch --show-current 2>/dev/null || git rev-parse --abbrev-ref HEAD
      git log -1 --oneline 2>/dev/null || true
      printf '\nStatus:\n'
      git status -sb 2>/dev/null || true
    else
      printf 'Not a git repo: %s\n' "$DSP_REPO_DIR"
    fi

    printf '\n=== DSP ===\n'
    if command -v dsp >/dev/null 2>&1; then
      dsp --version 2>/dev/null || dsp --help 2>&1 | head -5
    else
      printf 'dsp command not found on PATH\n'
    fi

    printf '\n=== Config (%s) ===\n' "$CONFIG_FILE"
    if [[ -f "$CONFIG_FILE" ]]; then
      cat "$CONFIG_FILE"
    else
      printf '(missing)\n'
    fi
  } >"$log" 2>&1

  if has_whiptail; then
    whiptail --title "Version / status" --scrolltext --textbox "$log" 22 78 2>/dev/null || true
  else
    cat "$log"
    read -r -p "Press Enter to continue..."
  fi
  rm -f "$log"
}

main() {
  ensure_config_dir
  # Ubuntu's /etc/newt/palette uses entry=,magenta — typed CIDR text is nearly
  # invisible (dark red on magenta). Force a high-contrast entry field.
  export NEWT_COLORS='
root=white,blue
border=black,white
window=black,white
shadow=black,gray
title=black,white
button=black,white
buttonact=white,blue
compactbutton=black,white
checkbox=black,white
entry=black,white
disentry=gray,white
label=black,white
listbox=black,white
actlistbox=white,blue
actsellistbox=black,cyan
textbox=black,white
acttextbox=black,cyan
helpline=white,blue
roottext=white,blue
emptyscale=white,blue
'
  unset NEWT_COLORS_FILE
  while true; do
    choice="$(pick_choice || true)"
    case "${choice:-}" in
      1) do_update ;;
      2) do_configure ;;
      3) do_run ;;
      4) do_show_report ;;
      5) do_show_status ;;
      6) exit 0 ;;
      "")
        ;;
      *)
        err "Invalid choice: ${choice}"
        ;;
    esac
  done
}

main "$@"
