"""HTTP protocol library — Phase 4 HTTP Follow-up."""

from dsp.protocols.http.client import HttpClient, send_request
from dsp.protocols.http.events import (
    HTTP_FOLLOWUP_COMPLETED,
    HTTP_FOLLOWUP_STARTED,
    HTTP_FOLLOWUP_TRAFFIC_EVENTS,
    HTTP_REQUEST_CREATED,
    HTTP_REQUEST_ERROR,
    HTTP_REQUEST_SENT,
    HTTP_RESPONSE_RECEIVED,
    append_outcome_event,
    build_http_followup_completed_event,
    build_http_followup_started_event,
    build_http_request_created_event,
    build_http_request_error_event,
    build_http_request_sent_event,
    build_http_response_received_event,
)
from dsp.protocols.http.reporting import build_http_followup_report_section, http_followup_report_profile
from dsp.protocols.http.urls import (
    FIXED_PATHS,
    MAX_HOSTS_DEFAULT,
    MAX_REQUESTS_PER_HOST_DEFAULT,
    MAX_REQUESTS_TOTAL_DEFAULT,
    PORT_PRIORITY,
    PlannedHttpRequest,
    build_url,
    plan_followup_requests,
    select_port_for_host,
)
from dsp.protocols.http.sqli_events import (
    SQL_INJECTION_COMPLETED,
    SQL_INJECTION_STARTED,
    SQL_INJECTION_TRAFFIC_EVENTS,
    SQL_PAYLOAD_GENERATED,
    SQL_REQUEST_ERROR,
    SQL_REQUEST_SENT,
    SQL_RESPONSE_RECEIVED,
    append_sqli_outcome_event,
    build_sql_injection_completed_event,
    build_sql_injection_started_event,
    build_sql_payload_generated_event,
    build_sql_request_error_event,
    build_sql_request_sent_event,
    build_sql_response_received_event,
)
from dsp.protocols.http.sqli_payloads import (
    SQLI_CORE_REPEATS_PER_PATTERN,
    SQLI_CORE_TIME_BASED_CATEGORY,
    SQLI_CORE_UNION_SELECT_CATEGORY,
    SQLI_PATHS,
    SQLI_PAYLOADS,
    SQLI_REPEATS_PER_PATH,
    SQLI_REQUESTS_PER_HOST,
    PlannedSqliRequest,
    build_sqli_url,
    plan_sqli_requests,
    sql_injection_request_items,
)
from dsp.protocols.http.sqli_reporting import build_sql_injection_report_section, sql_injection_report_profile
from dsp.protocols.http.sqli_validation import SQL_INJECTION_METRIC_NAMES, sql_injection_validation_profile
from dsp.protocols.http.validation import HTTP_FOLLOWUP_METRIC_NAMES, http_followup_validation_profile

__all__ = [
    "FIXED_PATHS",
    "HTTP_FOLLOWUP_COMPLETED",
    "HTTP_FOLLOWUP_METRIC_NAMES",
    "HTTP_FOLLOWUP_STARTED",
    "HTTP_FOLLOWUP_TRAFFIC_EVENTS",
    "HTTP_REQUEST_CREATED",
    "HTTP_REQUEST_ERROR",
    "HTTP_REQUEST_SENT",
    "HTTP_RESPONSE_RECEIVED",
    "MAX_HOSTS_DEFAULT",
    "MAX_REQUESTS_PER_HOST_DEFAULT",
    "MAX_REQUESTS_TOTAL_DEFAULT",
    "PORT_PRIORITY",
    "SQLI_CORE_REPEATS_PER_PATTERN",
    "SQLI_CORE_TIME_BASED_CATEGORY",
    "SQLI_CORE_UNION_SELECT_CATEGORY",
    "SQLI_PATHS",
    "SQLI_PAYLOADS",
    "SQLI_REPEATS_PER_PATH",
    "SQLI_REQUESTS_PER_HOST",
    "SQL_INJECTION_COMPLETED",
    "SQL_INJECTION_METRIC_NAMES",
    "SQL_INJECTION_STARTED",
    "SQL_INJECTION_TRAFFIC_EVENTS",
    "SQL_PAYLOAD_GENERATED",
    "SQL_REQUEST_ERROR",
    "SQL_REQUEST_SENT",
    "SQL_RESPONSE_RECEIVED",
    "HttpClient",
    "PlannedSqliRequest",
    "PlannedHttpRequest",
    "append_outcome_event",
    "append_sqli_outcome_event",
    "build_http_followup_completed_event",
    "build_http_followup_report_section",
    "build_http_followup_started_event",
    "build_http_request_created_event",
    "build_http_request_error_event",
    "build_http_request_sent_event",
    "build_http_response_received_event",
    "build_sql_injection_completed_event",
    "build_sql_injection_report_section",
    "build_sql_injection_started_event",
    "build_sql_payload_generated_event",
    "build_sql_request_error_event",
    "build_sql_request_sent_event",
    "build_sql_response_received_event",
    "build_sqli_url",
    "build_url",
    "http_followup_report_profile",
    "http_followup_validation_profile",
    "plan_followup_requests",
    "plan_sqli_requests",
    "sql_injection_request_items",
    "sql_injection_report_profile",
    "sql_injection_validation_profile",
    "select_port_for_host",
    "send_request",
]
